# Generated by Django 4.1.1 on 2022-10-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('idEsp', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('nombreEspacio', models.CharField(default=0, max_length=30)),
                ('caracteristicas', models.CharField(default=0, max_length=50)),
                ('tiempoEsp', models.IntegerField()),
                ('disponibleEsp', models.BooleanField()),
                ('capacidad', models.IntegerField()),
                ('fechaEsp', models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.CharField(default=0, max_length=30)),
                ('tipoRes', models.CharField(default=0, max_length=20)),
                ('numS', models.CharField(default=0, max_length=50)),
                ('estatus', models.BooleanField()),
                ('tiempoRes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('idSoft', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('fechaSoft', models.CharField(default=0, max_length=30)),
                ('tipoSoft', models.CharField(default=0, max_length=20)),
                ('caracteristicas', models.CharField(default=0, max_length=50)),
                ('tiempoSoft', models.IntegerField()),
                ('disponibleSoft', models.BooleanField()),
            ],
        ),
    ]
