# Generated by Django 4.1.1 on 2022-10-17 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEq', models.CharField(default=0, max_length=30)),
                ('tipoEq', models.CharField(default=0, max_length=20)),
                ('caracteristicas', models.CharField(default=0, max_length=50)),
                ('tiempoEq', models.CharField(default=0, max_length=500)),
                ('disponibleEq', models.CharField(default=0, max_length=500)),
                ('imageEq', models.ImageField(default='', upload_to='cyber/static')),
                ('isActive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Espacios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEspacio', models.CharField(default=0, max_length=30)),
                ('caracteristicas', models.CharField(default=0, max_length=500)),
                ('tiempoEsp', models.CharField(default=0, max_length=500)),
                ('disponibleEsp', models.CharField(default=0, max_length=500)),
                ('capacidad', models.CharField(default=0, max_length=500)),
                ('fechaEsp', models.CharField(default=0, max_length=30)),
                ('imageEsp', models.ImageField(default='', upload_to='cyber/static')),
                ('isActive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Softwares',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaSoft', models.CharField(default=0, max_length=30)),
                ('tipoSoft', models.CharField(default=0, max_length=20)),
                ('caracteristicas', models.CharField(default=0, max_length=50)),
                ('tiempoSoft', models.CharField(default=0, max_length=500)),
                ('disponibleSoft', models.CharField(default=0, max_length=500)),
                ('imageSoft', models.ImageField(default='', upload_to='cyber/static')),
                ('isActive', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=0, max_length=30)),
                ('password', models.CharField(default=0, max_length=50)),
                ('email', models.CharField(default=0, max_length=50)),
                ('phone', models.CharField(default=0, max_length=50)),
                ('school', models.CharField(default=0, max_length=50)),
                ('rol', models.CharField(default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(default=0, max_length=30)),
                ('tipoRes', models.CharField(default=0, max_length=20)),
                ('estatus', models.CharField(default=0, max_length=500)),
                ('tiempoRes', models.CharField(default=0, max_length=500)),
                ('codigo', models.CharField(default=0, max_length=50)),
                ('idServicio', models.CharField(default=0, max_length=50)),
                ('hora', models.CharField(default=0, max_length=50)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cyber.usuarios')),
            ],
        ),
    ]
