# Generated by Django 4.1.1 on 2022-10-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='fechaEq',
        ),
        migrations.RemoveField(
            model_name='espacios',
            name='fechaEsp',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='fechaSoft',
        ),
    ]
