# Generated by Django 4.1.1 on 2022-10-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0004_espacios_imageesp_espacios_tipoesp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacios',
            name='imageEsp',
            field=models.ImageField(default='', upload_to='cyber/static/imagenesDB'),
        ),
    ]
