# Generated by Django 4.1.1 on 2022-10-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0005_alter_espacios_imageesp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacios',
            name='imageEsp',
            field=models.ImageField(default='', upload_to='cyber/static'),
        ),
    ]
