# Generated by Django 4.1.1 on 2022-10-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0006_alter_espacios_imageesp'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='imageEq',
            field=models.ImageField(default='', upload_to='cyber/static'),
        ),
        migrations.AddField(
            model_name='softwares',
            name='imageSoft',
            field=models.ImageField(default='', upload_to='cyber/static'),
        ),
    ]
