# Generated by Django 4.1.1 on 2022-10-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0007_equipos_imageeq_softwares_imagesoft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='idEq',
        ),
        migrations.RemoveField(
            model_name='espacios',
            name='idEsp',
        ),
        migrations.RemoveField(
            model_name='espacios',
            name='tipoEsp',
        ),
        migrations.RemoveField(
            model_name='softwares',
            name='idSoft',
        ),
        migrations.AddField(
            model_name='equipos',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='espacios',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='softwares',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='disponibleEq',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='tiempoEq',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='espacios',
            name='capacidad',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='espacios',
            name='disponibleEsp',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='espacios',
            name='tiempoEsp',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='estatus',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='tiempoRes',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='softwares',
            name='disponibleSoft',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='softwares',
            name='tiempoSoft',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
