# Generated by Django 4.1.1 on 2022-10-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0009_alter_equipos_id_alter_espacios_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='espacios',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='softwares',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
