# Generated by Django 4.1.1 on 2022-10-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0011_reservas_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=0, max_length=30)),
                ('password', models.CharField(default=0, max_length=50)),
                ('email', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
