# Generated by Django 4.1.1 on 2022-10-13 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0012_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='username',
        ),
    ]
