# Generated by Django 4.1.1 on 2022-10-13 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyber', '0013_rename_nombre_usuarios_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cyber.usuarios'),
        ),
    ]
